travis:
  secure:
    BINSTAR_TOKEN: L4L55eCdd/m1oX2RLxwzA/GKnKmtRB2dGy0BcxXXOBohIjeHNNfLmf/EZKHcicVXvW1ab0Y1k4y0yBpIv3ct7R4sVgKV6BB7J6+ggzlvApD7frj6BtcLIu7n2DzgmehqZfREj7rwldDV6pf64iGm80mPX9luyFadLMMWZgwo0/itETWW9ySZMhZ6A/EaUEy9OhSAa7J9pLOPnUGEwL36fzhqiHvIQy2TrRsJyOPQQfje/szT/4oaEFlsCBZFuMIPNvdL6oxva4n9R34AEjiW3CSYNN/1I7ZUci8XM9UIaMByJ/FxUmdj9QMeyTDxWRbR2/cr4fPTNHyQXn9//Shrt9UFv8SF+OVJzoZFBBfAC+xLcDA7haWnEieGOnVnHz3PF1TryhIIb5D4/UkwFyPdaJBln6oEKpTp0cPJZQtajgb2ROmlwbOPmYOktyCkSRvUlSVKPyxwH7Eu1iwZaCcJfHkXctAZl1WNL75jdjk6266GsRnqkLaMwrNzAf+A/R1hI+s6X+JZHLz5wo7CKtVLcqkszRKILGfMRq4rbCpjRgaMmqiBj7mP/QaCdCsZ3oQ1qlY0bjRz5PlBa3e7+eVLoxkByNyhZjgwkaKLmAjPQ9feFY+AW4g51yLfeEEpb5gm8jyhWUY3eQIKOfs+F+cgUJXYXGdrzbDpY19xTURarm4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
