travis:
  secure:
    BINSTAR_TOKEN: 1lXwcCTkQGdLbpknCAGYVQ25SFvwdPomdHJ7hiCA4tfeI8SDrrpDD3EDrKn7tZ8rv+9W04vWZU5lg+b8knEgns+2NRSQmPtcDCOEBu11LScyQt2hsXXapHmNPoUvunObbR8ickMU5uV309j2/SFGpa04HYoC0nyMPcsN35DTsSU/X/J2LP8SRk1K++wDdlzZ7T3XT/x43m6OauX9SbF6j+wEGDA/0iv1Prc4yjat4JhR27spumnqrEiazkLr5yCMzXmzsziaP0U7TBLrHDR9rMEdUIhCxEax521Axc+Gadi5DoYCnWroqp7Iyetq68oCYuOcQA3ASBscNaggDiFPVSou1NRoUmudw/NLSDQ2CVcs4pQhunRoDRmn16mIrccN3o0FKG4StUDXfXEtnZqOarDmpQCZ6bbIaOgWaqVJwQlDqTvJreQcefbYUaE65NpAFjImyGlz9taSjqH37wDjj0ptMqkJYVHCXMQqkklVQ2T29z5rW+3XUhTz+OnwLL7bMpev0mxlXk6bYjUJ+4Preqe1ATVvuzgw9d+XV0TYV5p6IxKg1d6PQljHk4uzsv2bcm6NdrtcOoyNjiMOpsZPDvuqkEq3CanTXtZlw4OHmXi+i6oN/lq/sAnXwacMI6tbAZKD1g3FV5SvW5MrRzs/+ppYIz9Zn5Ri5VU8ggtxbtk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
